framework:
    messenger:
        failure_transport: failed

        transports:
            incoming_messages:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: incoming_messages
                        type: direct
                        default_publish_routing_key: incoming_messages
                    queues:
                        incoming_messages:
                            binding_keys: [incoming_messages]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            summary_jobs:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: summary_jobs
                        type: direct
                        default_publish_routing_key: summary_jobs
                    queues:
                        summary_jobs:
                            binding_keys: [summary_jobs]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            publish_jobs:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: publish_jobs
                        type: direct
                        default_publish_routing_key: publish_jobs
                    queues:
                        publish_jobs:
                            binding_keys: [publish_jobs]
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2

            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Message\IncomingTelegramUpdateMessage: incoming_messages
            App\Message\SummaryJobMessage: summary_jobs
            App\Message\PublishJobMessage: publish_jobs
